version: "3.8"
services:
  postgres:
    image: postgres:14.0
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: consensus
      POSTGRES_DB: consensus
      POSTGRES_PASSWORD: 1
    networks:
      home_logrus:
        ipv4_address: 10.5.0.23
    ports:
      - "5432:5432"
    volumes:
      - /v/postgres:/var/lib/postgresql/data

  back:
    restart: always
    build:
      context: ./back
      args:
        - VERSION=${VERSION}
    image: ghcr.io/logrus-dev/consensus-back:${VERSION}
    container_name: back
    depends_on:
      - postgres
    ports:
      - "5001:5000"
    networks:
      home_logrus:
        ipv4_address: 10.5.0.21
    env_file:
    - .env

  front:
    restart: always
    build: ./front
    image: ghcr.io/logrus-dev/consensus-front:${VERSION}
    container_name: front
    ports:
      - "5002:80"
    networks:
      home_logrus:
        ipv4_address: 10.5.0.22

networks:
  home_logrus:
    external: true