version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: consensus
      POSTGRES_DB: consensus
      POSTGRES_PASSWORD: 1
    networks:
      homelogrusdev_logrus:
        ipv4_address: 10.5.0.23
    ports:
      - "5432:5432"

  back:
    restart: always
    image: ghcr.io/logrus-dev/consensus-back:1.0.15
    container_name: back
    depends_on:
      - postgres
    networks:
      homelogrusdev_logrus:
        ipv4_address: 10.5.0.21
    env_file:
    - .env

  front:
    restart: always
    image: ghcr.io/logrus-dev/consensus-front:1.0.3
    container_name: front
    networks:
      homelogrusdev_logrus:
        ipv4_address: 10.5.0.22

networks:
  homelogrusdev_logrus:
    external: true